name: Build

on: 
  pull_request:
    types: [opened, synchronize]
  

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]

    runs-on:  ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Run unit tests
      run: dotnet test Tocsoft.PerformanceTester.Tests/Tocsoft.PerformanceTester.Tests.csproj --configuration Release  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:UseSourceLink=true /p:Exclude=[xunit.*]*
    - name: Update codecov
      uses: iansu/codecov-action-node@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./Tocsoft.PerformanceTester.Tests/coverage.opencover.xml #optional
        flags: unittests #optional
