name: Build

on: 
  pull_request:
    types: [opened, synchronize]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: Run unit tests
      run: dotnet test Tocsoft.PerformanceTester.Tests/Tocsoft.PerformanceTester.Tests.csproj --configuration Release