name: Build

on: 
  pull_request:
    types: [opened, synchronize]
  

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Run unit tests
      run: dotnet test Tocsoft.PerformanceTester.Tests/Tocsoft.PerformanceTester.Tests.csproj --configuration Release  --collect:"XPlat Code Coverage"
    - run : cp Tocsoft.PerformanceTester.Tests/TestResults/*/coverage.cobertura.xml ./coverage.xml
    - uses: iansu/codecov-action-node@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./coverage.xml #optional
        flags: unittests #optional
