name: Publish

on: 
  push:
    branches: master
    paths: 
      - 'Tocsoft.PerformanceTester/**'
jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
      
    - name: Build with dotnet
      run: dotnet pack --configuration Release -o ../output

    - name: setup nuget
      if: success()
      run: sudo apt install nuget
    - name: Configure feed
      if: success()
      run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/${{github.actor}}/index.json" -UserName ${{github.actor}} -Password ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to nightly feed
      if: success()
      run: nuget push  -Source "GitHub" output/*.nupkg
    
