name: Publish

on: 
  push:
    branches: master
#    paths: 
#      - 'Tocsoft.PerformanceTester/**'
jobs:
  publish:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v1
   # - name: Setup .NET Core
   #   uses: actions/setup-dotnet@v1
   #   with:
   #     dotnet-version: 2.2.108
      
    - name: Build with dotnet
      run: dotnet pack --configuration Release

  #  - name: Publish package
  #    run: curl -vX PUT -u "${{github.actor}}:TOKEN" -F package=@**/bin/Release/*.nupkg https://nuget.pkg.github.com/${{github.actor}}/
    - name: Configure feed
      if: success()
      run: nuget.exe source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/${{github.actor}}/index.json" -UserName ${{github.actor}} -Password ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to nightly feed
      if: success()
      run: nuget.exe push  -Source "GitHub" **/bin/Release/*.nupkg
    
